language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
before_install:
  - gem update --system
  - gem install bundler -v 1.16.1
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
